name: "Deploy Infrastructure"

on:
    push:
        branches:
            - main
            - dev


env:
    AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
    AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    AWS_REGION: ${{ secrets.AWS_REGION }}


jobs:
    DeployInfra:
        name: Execute Terraform code
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Setup Python
              uses: actions/setup-python@v4
              with:
                python-version: "3.11"
            
            - name: Config terraform values
              run: |
                cd devops_helper_scripts
                pip install boto3
                python3 configure_terraform_values.py

            - name: Setup Terraform 
              uses: hashicorp/setup-terraform@v2

            - name: Terraform Apply
              run: |
                cd iac
                terraform init
                terraform destroy -auto-approve

                

                